[package]
name = "ipld-collections"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
libipld = { path = "../rust-ipld" }
dag-cbor-derive = { path = "../rust-ipld/dag-cbor-derive" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "list"
harness = false

[[bench]]
name = "map"
harness = false

[profile.release]
debug = true
