[package]
name = "ipld-collections"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
async-std = "1.5.0"
ipld-block-builder = { path = "../ipld-block-builder" }
libipld = "0.2.2"
thiserror = "1.0.18"

[dev-dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
criterion = "0.3"
ipfs-embed = { path = "../ipfs-embed" }
model = "0.1"
tempdir = "0.3"

[[bench]]
name = "list"
harness = false

[[bench]]
name = "map"
harness = false

[profile.release]
debug = true

[patch.crates-io]
libipld = { path = "../rust-ipld" }
