[package]
name = "ipld-vec"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
libipld = { path = "../rust-ipld" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "vec"
harness = false

[profile.release]
debug = true
