[package]
name = "ipld-collections"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
dag-cbor-derive = { path = "../rust-ipld/dag-cbor-derive" }
failure = "0.1"
libipld = { path = "../rust-ipld" }

[dev-dependencies]
async-std = "0.99"
criterion = "0.3"
ipld-daemon-client = { path = "../rust-ipld-daemon/client" }
model = "0.1"
tempdir = "0.3"

[[bench]]
name = "list"
harness = false

[[bench]]
name = "map"
harness = false

[profile.release]
debug = true
